version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose the application on port 8080
    environment:
      - UVICORN_WORKERS=4 # Example: Custom environment variable for FastAPI/uvicorn
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 
    restart: unless-stopped
